
import { motion, AnimatePresence } from 'framer-motion';
import { X, Shield, FileText, Database, Lock } from 'lucide-react';

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function TermsModal({ isOpen, onClose }: TermsModalProps) {
  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/80 backdrop-blur-md"
          />
          
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="relative w-full max-w-2xl max-h-[85vh] bg-[#050505] border border-white/10 rounded-[2rem] shadow-[0_0_50px_rgba(0,0,0,1)] overflow-hidden flex flex-col"
          >
            {/* Header */}
            <div className="p-8 border-b border-white/5 bg-gradient-to-r from-primary/10 to-transparent flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="p-3 rounded-2xl bg-primary/10 text-primary border border-primary/20 shadow-[0_0_15px_rgba(58,134,255,0.2)]">
                  <Shield className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-white uppercase tracking-tighter">Terms of Service</h3>
                  <p className="text-[10px] text-primary font-black uppercase tracking-[0.2em] mt-0.5 opacity-80">
                    Sovereign Infrastructure Protocol (v6.0)
                  </p>
                </div>
              </div>
              <button 
                onClick={onClose}
                className="p-2 rounded-full hover:bg-white/5 text-gray-500 hover:text-white transition-all"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            {/* Sovereign Badges */}
            <div className="px-8 py-4 bg-white/[0.02] border-b border-white/5">
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-[9px] px-2.5 py-1 rounded-md bg-white/5 text-gray-400 font-mono uppercase tracking-widest border border-white/10">
                    [ FAIL-CLOSED ]
                </span>
                <span className="text-[9px] px-2.5 py-1 rounded-md bg-primary/5 text-primary/80 font-mono uppercase tracking-widest border border-primary/10">
                    [ AUDIT-READY ]
                </span>
                <span className="text-[9px] px-2.5 py-1 rounded-md bg-secondary/5 text-secondary/80 font-mono uppercase tracking-widest border border-secondary/10">
                    [ DATA-SOVEREIGN ]
                </span>
                <span className="text-[9px] px-2.5 py-1 rounded-md bg-emerald-500/5 text-emerald-500/80 font-mono uppercase tracking-widest border border-emerald-500/10">
                    [ DETERMINISTIC ]
                </span>
              </div>
            </div>

            {/* Content Container */}
            <div className="flex-1 overflow-y-auto p-8 space-y-8 text-sm leading-relaxed text-gray-400 font-light custom-scrollbar">
              
              {/* Section 1: Ownership */}
              <section className="space-y-4">
                <div className="flex items-center gap-3 text-white font-bold uppercase tracking-widest text-[11px]">
                  <Database className="w-4 h-4 text-primary" />
                  1. Data Ownership & Stewardship
                </div>
                <div className="pl-7 border-l border-white/5 space-y-3 font-light">
                   <p>
                    All operational data generated by a partner (User) remains the property of that partner. 
                    GUAW acts exclusively as a <span className="text-white font-medium">Technical Data Steward</span>, providing secure custody, integrity enforcement, and forensic traceability — never ownership.
                   </p>
                   <ul className="list-disc pl-4 space-y-1 text-xs text-gray-500">
                      <li>No commercial exploitation: GUAW does not sell or trade partner data.</li>
                      <li>Zero-Knowledge Integrity: Data is processed strictly to preserve system consistency.</li>
                      <li>Export on Demand: Partners may export structured data at any time.</li>
                   </ul>
                </div>
              </section>

              {/* Section 2: Zero-Knowledge */}
              <section className="space-y-4">
                <div className="flex items-center gap-3 text-white font-bold uppercase tracking-widest text-[11px]">
                  <Shield className="w-4 h-4 text-primary" />
                  2. Zero-Knowledge Integrity
                </div>
                <div className="pl-7 border-l border-white/5 space-y-3 font-light">
                   <p>
                    Data is processed exclusively to maintain deterministic system integrity using zero-knowledge proofs; raw data is never exposed.
                   </p>
                   <p className="text-xs text-gray-500 italic">
                    This technical guarantee ensures that GUAW can verify the physical authenticity of an event without ever accessing or storing the underlying semantic content.
                   </p>
                </div>
              </section>

              {/* Section 3: Forensic */}
              <section className="space-y-4">
                <div className="flex items-center gap-3 text-white font-bold uppercase tracking-widest text-[11px]">
                  <FileText className="w-4 h-4 text-secondary" />
                  3. Forensic Records & Evidence Integrity
                </div>
                <div className="pl-7 border-l border-white/5 space-y-3 font-light">
                   <p>
                    Critical system events are recorded in a <span className="text-white font-medium">tamper-resistant forensic ledger</span> (Lazarus Protocol) designed to preserve non-repudiation.
                   </p>
                   <p className="text-xs text-gray-500 italic">
                    GUAW does not interpret intent or assign responsibility; it preserves verifiable technical evidence of what occurred, exactly as recorded.
                   </p>
                </div>
              </section>

              {/* Section 4: Liability */}
              <section className="space-y-4">
                <div className="flex items-center gap-3 text-white font-bold uppercase tracking-widest text-[11px]">
                  <Lock className="w-4 h-4 text-alert" />
                  4. System Integrity, Availability & Liability
                </div>
                <p className="pl-7 border-l border-white/5">
                  GUAW operates under a <span className="text-white font-medium">Fail-Closed model</span>. If integrity risks are detected, the system may automatically restrict operations. 
                  Liability is limited to the faithful technical stewardship of the forensic record. We guarantee the integrity of the record, not the business outcome.
                </p>
              </section>

              {/* Section 5: Privacy */}
              <section className="space-y-4">
                <div className="flex items-center gap-3 text-white font-bold uppercase tracking-widest text-[11px]">
                  <Shield className="w-4 h-4 text-emerald-500" />
                  5. Privacy & Minimal Exposure
                </div>
                <div className="pl-7 border-l border-white/5 space-y-2">
                   <p>
                    Privacy is <span className="text-white font-medium">enforced by architecture</span>, not just by policy. GUAW avoids unnecessary data collection and employs no marketing or behavioral tracking.
                   </p>
                   <div className="text-[10px] font-mono text-emerald-500/70 uppercase tracking-widest">
                       Protocol: Minimization by Default // Essential Tokens Only
                   </div>
                </div>
              </section>

              {/* Section 6: Billing */}
              <section className="space-y-4">
                <div className="flex items-center gap-3 text-white font-bold uppercase tracking-widest text-[11px]">
                  <span className="text-sm">💳</span>
                  6. Service & Billing Policy
                </div>
                <div className="pl-7 border-l border-white/5 space-y-2 text-xs font-light text-gray-400">
                   <p>
                    GUAW operates on a <strong className="text-white">Fail-Secure Funding Model</strong>. Access to sovereign infrastructure is strictly contingent on active license status.
                   </p>
                   <ul className="list-none space-y-3 pt-2">
                        <li className="flex gap-4">
                            <span className="text-gray-500 font-mono text-[9px] w-20 flex-shrink-0 pt-0.5">EVALUATION</span>
                            <p>7-day free trial available; no automatic charges upon expiry.</p>
                        </li>
                        <li className="flex gap-4">
                            <span className="text-gray-500 font-mono text-[9px] w-20 flex-shrink-0 pt-0.5">PREPAID</span>
                            <p>Monthly billing in advance. Non-refundable (“Fail-Secure Funding”).</p>
                        </li>
                        <li className="flex gap-4">
                            <span className="text-gray-500 font-mono text-[9px] w-20 flex-shrink-0 pt-0.5">HARD STOP</span>
                            <p>On cancellation or failed payment, API access terminates at the end of the paid period.</p>
                        </li>
                        <li className="flex gap-4">
                            <span className="text-gray-500 font-mono text-[9px] w-20 flex-shrink-0 pt-0.5">SOVEREIGN VETO</span>
                            <p>GUAW may revoke service for actors engaging in protocol abuse, without refund.</p>
                        </li>
                   </ul>
                </div>
              </section>

              {/* Ending Seal */}
              <div className="pt-8 border-t border-white/5 text-center space-y-4">
                <div className="inline-flex flex-col items-center">
                    <p className="text-[10px] font-mono text-gray-400 tracking-[0.3em] font-black uppercase">
                        A sovereign system where integrity precedes convenience.
                    </p>
                    <div className="h-px w-24 bg-gradient-to-r from-transparent via-primary/50 to-transparent mt-2"></div>
                </div>
              </div>

            </div>

            {/* Footer */}
            <div className="p-8 border-t border-white/5 bg-[#080808] flex items-center justify-between">
              <p className="text-[9px] font-mono text-gray-600 uppercase tracking-widest">
                STAMPED: 21.01.2026 / GUAW-SDR
              </p>
              <button
                onClick={onClose}
                className="px-10 py-4 rounded-xl bg-white text-black font-black uppercase tracking-widest text-[11px] hover:bg-primary hover:text-white transition-all shadow-[0_4px_20px_rgba(255,255,255,0.1)] active:scale-95"
              >
                Acknowledge
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
