import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { ArrowLeft, ShieldCheck, Lock, FileText, Database } from 'lucide-react';
import { ParticlesBackground } from '../../components/ui/ParticlesBackground';

export const LegalPage = () => {
    return (
        <div className="min-h-screen bg-black text-white relative">
            <ParticlesBackground />
            
            {/* Header */}
            <header className="fixed top-0 left-0 right-0 z-50 bg-black/50 backdrop-blur-xl border-b border-white/5">
                <div className="max-w-7xl mx-auto px-4 h-20 flex items-center justify-between">
                    <Link to="/" className="flex items-center gap-2 group">
                        <ArrowLeft size={20} className="text-gray-400 group-hover:text-primary transition-colors" />
                        <span className="font-mono text-sm uppercase tracking-tighter text-gray-400 group-hover:text-white transition-colors">Return to Surface</span>
                    </Link>
                    <div className="flex items-center gap-3">
                         <ShieldCheck className="text-primary" size={24} />
                         <span className="font-bold tracking-widest uppercase text-sm">Legal Framework v1.1-Sovereign</span>
                    </div>
                </div>
            </header>

            <main className="pt-32 pb-24 px-4 max-w-4xl mx-auto relative z-10">
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="space-y-16"
                >
                    {/* Intro */}
                    <div className="space-y-4">
                        <h1 className="text-4xl md:text-5xl font-bold tracking-tighter uppercase mb-2">Terms of Service & Data Sovereignty: <br/><span className="text-gray-600 italic">Operating within a Deterministic, Sovereign Infrastructure</span></h1>
                        <p className="text-gray-400 text-lg leading-relaxed max-w-4xl font-light italic">
                            By interacting with GUAW Guardians, you acknowledge that you are operating within a sovereign technical infrastructure. Our terms are defined by physics and deterministic proof, not just legal prose.
                        </p>
                    </div>

                    {/* Section 1 */}
                    <section className="space-y-6">
                        <div className="flex items-center gap-3 text-primary">
                            <Database size={24} />
                            <h2 className="text-2xl font-bold uppercase tracking-widest">1. Data Ownership & Stewardship</h2>
                        </div>
                        <div className="glass-dark p-8 rounded-2xl border border-white/5 space-y-6 text-gray-300 leading-relaxed font-light">
                            <p>
                                All operational data generated by partners (Users) remains their exclusive property. GUAW acts solely as a <strong className="text-white">Technical Data Steward</strong>, providing cryptographically verifiable custody, integrity enforcement, and audit-ready traceability. GUAW does not claim ownership, sell, or commercialize partner data under any circumstances.
                            </p>
                        </div>
                    </section>

                    {/* Section 2 */}
                    <section className="space-y-6">
                        <div className="flex items-center gap-3 text-primary">
                            <ShieldCheck size={24} />
                            <h2 className="text-2xl font-bold uppercase tracking-widest">2. Zero-Knowledge Integrity</h2>
                        </div>
                        <div className="glass-dark p-8 rounded-2xl border border-white/5 space-y-4 text-gray-300 leading-relaxed font-light">
                            <p>
                                Data is processed exclusively to maintain deterministic system integrity using zero-knowledge proofs; raw data is never exposed.
                            </p>
                            <p className="text-sm italic text-gray-400">
                                This technical guarantee ensures that GUAW can verify the physical authenticity of an event without ever accessing or storing the underlying semantic content.
                            </p>
                        </div>
                    </section>

                    {/* Section 3 */}
                    <section className="space-y-6">
                        <div className="flex items-center gap-3 text-secondary">
                            <FileText size={24} />
                            <h2 className="text-2xl font-bold uppercase tracking-widest">3. Forensic Records & Evidence Integrity</h2>
                        </div>
                        <div className="glass-dark p-8 rounded-2xl border border-white/5 space-y-4 text-gray-300 leading-relaxed font-light">
                            <p>
                                Critical system events are immutably recorded in the <strong className="text-white uppercase tracking-tighter">Lazarus Protocol</strong> forensic ledger, preserving tamper-resistant evidence suitable for audits, compliance verification, or dispute resolution. 
                            </p>
                            <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5 border-l-secondary border-l-2">
                                <p className="text-sm italic">
                                    GUAW documents what occurred, but does not interpret intent or assign legal responsibility.
                                </p>
                            </div>
                        </div>
                    </section>

                    {/* Section 4 */}
                    <section className="space-y-6">
                        <div className="flex items-center gap-3 text-alert">
                            <Lock size={24} />
                            <h2 className="text-2xl font-bold uppercase tracking-widest">4. System Integrity, Availability & Liability</h2>
                        </div>
                        <div className="glass-dark p-8 rounded-2xl border border-white/5 space-y-4 text-gray-300 leading-relaxed font-light">
                            <p>
                                GUAW enforces a <strong className="text-white uppercase tracking-tighter">Fail-Closed model</strong> to ensure system integrity. Detected anomalies may automatically restrict operations to protect correctness and data sovereignty. 
                            </p>
                            <p className="text-sm">
                                Liability is strictly limited to accurate technical stewardship of the forensic record; GUAW does not guarantee specific business outcomes or decisions made by partners.
                            </p>
                        </div>
                    </section>

                    {/* Section 5 */}
                    <section className="space-y-6">
                        <div className="flex items-center gap-3 text-emerald-500">
                            <ShieldCheck size={24} />
                            <h2 className="text-2xl font-bold uppercase tracking-widest">5. Privacy & Minimal Exposure</h2>
                        </div>
                        <div className="glass-dark p-8 rounded-2xl border border-white/5 space-y-4 text-gray-300 leading-relaxed font-light">
                            <p>
                                Privacy is enforced by architecture, not policy. The platform minimizes personal data collection, employs no tracking or marketing cookies, and uses technical signals exclusively for security and operational continuity.
                            </p>
                        </div>
                    </section>

                    {/* Section 6 - Billing */}
                    <section className="space-y-6">
                        <div className="flex items-center gap-3 text-white">
                            <span className="text-2xl">💳</span>
                            <h2 className="text-2xl font-bold uppercase tracking-widest">6. Service & Billing Policy</h2>
                        </div>
                        <div className="glass-dark p-8 rounded-2xl border border-white/5 space-y-4 text-gray-300 leading-relaxed font-light">
                            <p>
                                GUAW operates on a <strong className="text-white">Fail-Secure Funding Model</strong>. Access to sovereign infrastructure is strictly contingent on active license status.
                            </p>
                            <ul className="list-none space-y-4 text-sm tracking-tight">
                                <li className="flex gap-4">
                                    <span className="text-gray-500 font-mono text-[10px] w-24 flex-shrink-0 pt-1">EVALUATION</span>
                                    <p className="text-gray-400">7-day free trial available; no automatic charges upon expiry.</p>
                                </li>
                                <li className="flex gap-4">
                                    <span className="text-gray-500 font-mono text-[10px] w-24 flex-shrink-0 pt-1">PREPAID</span>
                                    <p className="text-gray-400">Monthly billing in advance. Non-refundable (“Fail-Secure Funding”).</p>
                                </li>
                                <li className="flex gap-4">
                                    <span className="text-gray-500 font-mono text-[10px] w-24 flex-shrink-0 pt-1">HARD STOP</span>
                                    <p className="text-gray-400">On cancellation or failed payment, API access terminates at the end of the paid period; no grace periods.</p>
                                </li>
                                <li className="flex gap-4">
                                    <span className="text-gray-500 font-mono text-[10px] w-24 flex-shrink-0 pt-1">SOVEREIGN VETO</span>
                                    <p className="text-gray-400">GUAW may revoke service for actors engaging in protocol abuse or malicious activity, without refund.</p>
                                </li>
                            </ul>
                        </div>
                    </section>

                    {/* Footer Legal */}
                    <div className="pt-16 border-t border-white/5 text-center space-y-4">
                        <p className="text-[10px] text-gray-600 font-mono tracking-widest uppercase italic">
                            A sovereign infrastructure where integrity precedes convenience.
                            <br/>
                             <span className="text-gray-400">GUAW™. ALL RIGHTS RESERVED. RECORD REF: 2026.02.SOV-6</span>
                        </p>
                    </div>
                </motion.div>
            </main>
        </div>
    );
};
